from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Literal
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, field_validator

from apps.backend.app.schemas.character import Emotion


PROTOCOL_VERSION = 2
LEGACY_PROTOCOL_VERSION = 1
SUPPORTED_PROTOCOL_VERSIONS = (LEGACY_PROTOCOL_VERSION, PROTOCOL_VERSION)
# A 48 kHz mono WAV has a larger base64 representation than the former 1 MB
# guard after only a short natural sentence.  Stream segments are bounded by
# the live TTS text limits and are generated by this backend, so 6 MB keeps the
# protocol safe while allowing a complete thought to reach the avatar.
MAX_STREAM_AUDIO_BASE64_CHARS = 6_000_000
GESTURE_TAGS = frozenset({
    "none", "auto", "talk", "greeting", "agreement", "disagreement",
    "question", "explanation", "thinking", "surprise", "frustration",
    "farewell", "shrug",
})
AVATAR_PRESENCE_STATES = frozenset({"idle", "listening", "thinking", "speaking"})


def normalize_gesture(value: object) -> str:
    """Keep transport forwards-compatible: unsupported semantic tags become auto."""
    raw = getattr(value, "value", value)
    normalized = str(raw or "auto").strip().lower()
    return normalized if normalized in GESTURE_TAGS else "auto"


def normalize_avatar_presence(value: object) -> str:
    normalized = str(value or "idle").strip().lower()
    return normalized if normalized in AVATAR_PRESENCE_STATES else "idle"


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


class ProtocolModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class Envelope(ProtocolModel):
    protocol_version: Literal[1, 2] = PROTOCOL_VERSION
    type: str
    message_id: str = Field(default_factory=lambda: str(uuid4()))
    timestamp: datetime = Field(default_factory=utc_now)
    session_id: str = "default"


class SpeakPayload(ProtocolModel):
    utterance_id: str
    text: str = Field(min_length=1, max_length=8000)
    audio_url: str = Field(min_length=1, max_length=2048)
    emotion: Emotion = Emotion.NEUTRAL
    intent: str = "casual_chat"
    gesture: str = "auto"
    gesture_intensity: float = Field(default=1.0, ge=0.0, le=1.0)
    interrupt: bool = True

    _normalize_gesture = field_validator("gesture", mode="before")(normalize_gesture)


class StreamStartPayload(ProtocolModel):
    utterance_id: str
    emotion: Emotion = Emotion.THINKING
    intent: str = "casual_chat"
    interrupt: bool = True


class StreamMetadataPayload(ProtocolModel):
    utterance_id: str
    emotion: Emotion = Emotion.NEUTRAL
    gesture: str = "auto"
    gesture_intensity: float = Field(default=1.0, ge=0.0, le=1.0)


class StreamMotionCuePayload(ProtocolModel):
    """Optional per-spoken-segment movement hint for protocol-v2 renderers."""

    gesture: str = "auto"
    emphasized: bool = False

    _normalize_gesture = field_validator("gesture", mode="before")(normalize_gesture)


class StreamSegmentPayload(ProtocolModel):
    utterance_id: str
    sequence: int = Field(ge=0)
    audio_base64: str = Field(min_length=8, max_length=MAX_STREAM_AUDIO_BASE64_CHARS)
    format: Literal["wav"] = "wav"
    sample_rate: int = Field(default=24000, ge=8000, le=96000)
    channels: int = Field(default=1, ge=1, le=2)
    duration_seconds: float = Field(gt=0, le=120)
    is_final: bool = False
    motion: StreamMotionCuePayload = Field(default_factory=StreamMotionCuePayload)


class StreamEndPayload(ProtocolModel):
    utterance_id: str


class StreamReceiptPayload(ProtocolModel):
    utterance_id: str
    sequence: int = Field(ge=0)
    client_latency_ms: int = Field(ge=0, le=120_000)


class EmotionPayload(ProtocolModel):
    emotion: Emotion
    intensity: float = Field(default=1.0, ge=0.0, le=1.0)


class StopPayload(ProtocolModel):
    utterance_id: str | None = None


class AudioMutePayload(ProtocolModel):
    muted: bool = False


class OverlayPayload(ProtocolModel):
    visible: bool = True
    always_on_top: bool = True
    locked: bool = True
    scale: float = Field(default=1.0, ge=0.5, le=2.0)
    monitor: str = Field(default="primary", min_length=1, max_length=256)
    x: float = 80.0
    y: float = 80.0
    width: float = Field(default=640.0, ge=240.0, le=3840.0)
    height: float = Field(default=720.0, ge=240.0, le=2160.0)


class OverlayBoundsChangedPayload(ProtocolModel):
    x: float
    y: float
    width: float = Field(ge=240.0, le=3840.0)
    height: float = Field(ge=240.0, le=2160.0)


class GesturePayload(ProtocolModel):
    gesture: str = "auto"
    intensity: float = Field(default=1.0, ge=0.0, le=1.0)
    interrupt: bool = True

    _normalize_gesture = field_validator("gesture", mode="before")(normalize_gesture)


class StatePayload(ProtocolModel):
    state: str = "idle"

    _normalize_state = field_validator("state", mode="before")(normalize_avatar_presence)


class PingPayload(ProtocolModel):
    sent_at: datetime = Field(default_factory=utc_now)


class ErrorPayload(ProtocolModel):
    code: str
    message: str


class OutgoingMessage(Envelope):
    payload: dict[str, Any]


class HelloPayload(ProtocolModel):
    client_name: str = Field(min_length=1, max_length=256)
    client_version: str = Field(min_length=1, max_length=64)
    supported_protocol_versions: list[int] = Field(min_length=1, max_length=10)
    platform: str | None = Field(default=None, max_length=128)


class PongPayload(ProtocolModel):
    reply_to: str | None = None


class AckPayload(ProtocolModel):
    reply_to: str
    accepted: bool
    error: str | None = Field(default=None, max_length=512)


class PlaybackPayload(ProtocolModel):
    utterance_id: str
    reply_to: str | None = None
    reason: str | None = Field(default=None, max_length=512)
    client_latency_ms: int | None = Field(default=None, ge=0, le=120_000)


class ClientStatePayload(ProtocolModel):
    state: str = "idle"

    _normalize_state = field_validator("state", mode="before")(normalize_avatar_presence)


class MotionProfilePayload(ProtocolModel):
    profile: str = Field(min_length=1, max_length=64)


class IncomingMessage(Envelope):
    payload: dict[str, Any]


class AvatarStatusClient(ProtocolModel):
    client_id: str
    connected_at: datetime
    last_heartbeat_at: datetime
    client_name: str | None = None
    client_version: str | None = None
    platform: str | None = None
    state: str = "idle"
    current_utterance_id: str | None = None
    current_motion_profile: str | None = None
    current_gesture: str | None = None


class EmotionEngineStatus(ProtocolModel):
    mapping_valid: bool
    mapping_error: str | None = None
    current_emotion: Emotion = Emotion.NEUTRAL
    target_emotion: Emotion = Emotion.NEUTRAL
    intensity: float = Field(ge=0.0, le=1.0)
    gesture: str = "auto"
    motion_profile: str
    attack_ms: int = Field(ge=0)
    minimum_hold_ms: int = Field(ge=0)
    release_ms: int = Field(ge=0)
    source_utterance_id: str | None = None
    generation: int = Field(ge=0)
    speaking: bool


class AvatarStatusResponse(ProtocolModel):
    enabled: bool
    protocol_version: int = PROTOCOL_VERSION
    broadcast_policy: str = "all_connected_clients"
    client_count: int
    clients: list[AvatarStatusClient]
    emotion_engine: EmotionEngineStatus


class AvatarTestSpeakRequest(ProtocolModel):
    text: str = Field(min_length=1, max_length=1200)
    emotion: Emotion = Emotion.NEUTRAL
    intent: str = "test"
    gesture: str = "auto"
    gesture_intensity: float = Field(default=1.0, ge=0.0, le=1.0)
    session_id: str = "default"
    interrupt: bool = True

    _normalize_gesture = field_validator("gesture", mode="before")(normalize_gesture)


class AvatarTestEmotionRequest(ProtocolModel):
    emotion: Emotion
    intensity: float = Field(default=1.0, ge=0.0, le=1.0)
    session_id: str = "default"


class AvatarTestGestureRequest(GesturePayload):
    session_id: str = "default"


class AvatarStopRequest(ProtocolModel):
    utterance_id: str | None = None
    session_id: str = "default"


class AvatarOverlayPatch(ProtocolModel):
    visible: bool | None = None
    always_on_top: bool | None = None
    locked: bool | None = None
    scale: float | None = Field(default=None, ge=0.5, le=2.0)
    monitor: str | None = Field(default=None, min_length=1, max_length=256)
    x: float | None = None
    y: float | None = None
    width: float | None = Field(default=None, ge=240.0, le=3840.0)
    height: float | None = Field(default=None, ge=240.0, le=2160.0)
