"""Generate checked-in Character Protocol v3 artifacts from Pydantic.

Run with ``.venv\\Scripts\\python.exe scripts/generate_character_protocol.py``.
The JSON Schema is authoritative; the TypeScript and C# contracts deliberately
remain small DTOs so Unity can consume protocol frames without a Python runtime.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from apps.backend.app.schemas.character import CharacterTurn, Emotion, Gesture, Intent
SCHEMA_PATH = ROOT / "apps" / "protocol" / "character-turn.schema.json"
TS_PATH = ROOT / "apps" / "web" / "src" / "generated" / "character-protocol.ts"
CS_PATH = ROOT / "apps" / "protocol" / "generated" / "csharp" / "CharacterProtocolV3.cs"


def union(values: type[Emotion] | type[Gesture] | type[Intent]) -> str:
    return " | ".join(f'"{item.value}"' for item in values)


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def main() -> None:
    schema = CharacterTurn.model_json_schema()
    schema["$id"] = "https://neuroasist.local/schemas/character-turn-v3.json"
    schema["title"] = "Character Protocol v3"
    write(SCHEMA_PATH, json.dumps(schema, ensure_ascii=False, indent=2) + "\n")

    write(TS_PATH, f'''// Generated by scripts/generate_character_protocol.py. Do not edit.
export const CHARACTER_PROTOCOL_VERSION = 3 as const;
export type Emotion = {union(Emotion)};
export type Intent = {union(Intent)};
export type Gesture = {union(Gesture)};

export type AffectCue = {{ emotion: Emotion; intensity: number; valence: number; arousal: number }};
export type GestureCue = {{ name: Gesture; intensity: number; interrupt: boolean }};
export type DeliveryOverride = {{ segment: number; pace: "slow" | "normal" | "fast"; emphasis: "none" | "light" }};
export type DeliveryCue = {{ pace: "slow" | "normal" | "fast"; emphasis: number; overrides: DeliveryOverride[] }};
export type ContinuityCue = {{ referenced_memory_ids: string[]; referenced_episode_ids: string[]; closes_open_loop_ids: string[] }};
export type CharacterTurn = {{ protocol_version: 3; reply: string; intent: Intent; affect: AffectCue; gesture: GestureCue; delivery: DeliveryCue; continuity?: ContinuityCue | null }};
export type CharacterMetadataFrame = Omit<CharacterTurn, "reply">;
''')

    emotion_values = ", ".join(f'"{item.value}"' for item in Emotion)
    intent_values = ", ".join(f'"{item.value}"' for item in Intent)
    gesture_values = ", ".join(f'"{item.value}"' for item in Gesture)
    write(CS_PATH, f'''// Generated by scripts/generate_character_protocol.py. Do not edit.
using System;
using System.Collections.Generic;

namespace NeuroAsist.Protocol;

public static class CharacterProtocolV3
{{
    public const int Version = 3;
    public static readonly IReadOnlyList<string> Emotions = new[] {{ {emotion_values} }};
    public static readonly IReadOnlyList<string> Intents = new[] {{ {intent_values} }};
    public static readonly IReadOnlyList<string> Gestures = new[] {{ {gesture_values} }};
}}

public sealed class CharacterTurn
{{
    public int protocol_version {{ get; set; }} = CharacterProtocolV3.Version;
    public string reply {{ get; set; }} = "";
    public string intent {{ get; set; }} = "unknown";
    public AffectCue affect {{ get; set; }} = new();
    public GestureCue gesture {{ get; set; }} = new();
    public DeliveryCue delivery {{ get; set; }} = new();
    public ContinuityCue? continuity {{ get; set; }}
}}

public sealed class AffectCue {{ public string emotion {{ get; set; }} = "neutral"; public float intensity {{ get; set; }} = 1; public float valence {{ get; set; }}; public float arousal {{ get; set; }}; }}
public sealed class GestureCue {{ public string name {{ get; set; }} = "auto"; public float intensity {{ get; set; }} = 1; public bool interrupt {{ get; set; }} = true; }}
public sealed class DeliveryOverride {{ public int segment {{ get; set; }} = 1; public string pace {{ get; set; }} = "normal"; public string emphasis {{ get; set; }} = "none"; }}
public sealed class DeliveryCue {{ public string pace {{ get; set; }} = "normal"; public float emphasis {{ get; set; }}; public List<DeliveryOverride> overrides {{ get; set; }} = new(); }}
public sealed class ContinuityCue {{ public List<string> referenced_memory_ids {{ get; set; }} = new(); public List<string> referenced_episode_ids {{ get; set; }} = new(); public List<string> closes_open_loop_ids {{ get; set; }} = new(); }}
''')


if __name__ == "__main__":
    main()
